// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://purxymgnptnnldvbqity.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1cnh5bWducHRubmxkdmJxaXR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxODEzNDcsImV4cCI6MjA2Mzc1NzM0N30.lOvGHHAV1jA2tWliFcnIkY4tCgDEsi9YvJT2WiFPTA4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);